import type { Application, ApplicationEvent, Job } from "./types";

const iso = (d: string) => `${d}T09:00:00.000Z`;

export const SEED_JOBS: Job[] = [
  {
    id: "job-eri",
    title: "AI for Radio Networks",
    company: "Ericsson",
    location: "Stockholm",
    application_url: "https://jobs.ericsson.com/thesis/ai-radio-networks",
    release_date: "2026-08-25",
    deadline: "2026-10-10",
    categories: ["Machine Learning", "Signal Processing", "Communication"],
    priority: "High",
    notes: "Two students preferred. Supervisor mentioned reinforcement learning for scheduling.",
    job_description:
      "Investigate machine learning methods for radio resource management in 5G/6G networks. Work with large-scale network simulation data, design models for link adaptation and scheduling, and evaluate against classical baselines.",
    created_at: iso("2026-09-01"),
    updated_at: iso("2026-09-23"),
  },
  {
    id: "job-vol",
    title: "Machine Learning for Autonomous Systems",
    company: "Volvo Group",
    location: "Göteborg",
    application_url: "https://volvogroup.com/thesis/ml-autonomous",
    release_date: "2026-09-01",
    deadline: "2026-09-25",
    categories: ["Applied ML", "Robotics", "Computer Vision"],
    priority: "High",
    notes: "Ask about on-site presence in Göteborg. Deadline is close.",
    job_description:
      "Develop and evaluate perception and decision-making models for autonomous heavy vehicles operating in confined areas. Focus on robustness under adverse weather and sensor degradation.",
    created_at: iso("2026-09-02"),
    updated_at: iso("2026-09-23"),
  },
  {
    id: "job-sie",
    title: "AI-Based Fault Diagnosis for Gas Turbines",
    company: "Siemens Energy",
    location: "Finspång",
    application_url: "https://siemens-energy.com/thesis/fault-diagnosis",
    release_date: "2026-08-15",
    deadline: "2026-09-30",
    categories: ["Industrial AI", "Bayesian / Probabilistic ML", "Signal Processing"],
    priority: "Medium",
    notes: "Housing support available in Finspång.",
    job_description:
      "Use sensor time series from operating gas turbines to build data-driven fault detection and diagnosis. Compare probabilistic models with deep learning approaches and quantify uncertainty.",
    created_at: iso("2026-08-20"),
    updated_at: iso("2026-09-22"),
  },
  {
    id: "job-saa",
    title: "Sensor Fusion for Autonomous Navigation",
    company: "Saab",
    location: "Linköping",
    application_url: "https://saab.com/thesis/sensor-fusion-navigation",
    release_date: "2026-09-18",
    deadline: "2026-11-01",
    categories: ["Sensor Fusion", "SLAM", "Robotics"],
    priority: "Medium",
    notes: "Security clearance required — Swedish citizenship needed.",
    job_description:
      "Fuse IMU, GNSS and visual data for navigation in GNSS-denied environments. Implement and benchmark filtering and optimization based estimators on recorded flight data.",
    created_at: iso("2026-09-20"),
    updated_at: iso("2026-09-20"),
  },
  {
    id: "job-zen",
    title: "LLM Agents for Engineering Documentation",
    company: "Zenseact",
    location: "Göteborg",
    application_url: "https://zenseact.com/thesis/llm-agents",
    release_date: "2026-08-10",
    deadline: "2026-09-15",
    categories: ["LLM", "RAG", "NLP"],
    priority: "Low",
    notes: "Rejected — they picked a candidate with more NLP coursework.",
    job_description:
      "Build a retrieval augmented assistant over internal engineering documentation, with evaluation of grounding quality and hallucination rates.",
    created_at: iso("2026-08-12"),
    updated_at: iso("2026-09-16"),
  },
  {
    id: "job-sca",
    title: "Edge AI for Predictive Maintenance",
    company: "Scania",
    location: "Södertälje",
    application_url: "https://scania.com/thesis/edge-ai",
    release_date: "2026-09-10",
    deadline: "2026-10-20",
    categories: ["Embedded / Edge AI", "ML Engineering", "Industrial AI"],
    priority: "High",
    notes: "Need to rewrite motivation letter for embedded focus.",
    job_description:
      "Deploy compressed models on vehicle edge hardware for predictive maintenance, studying the trade-off between accuracy, latency and energy use.",
    created_at: iso("2026-09-12"),
    updated_at: iso("2026-09-21"),
  },
];

export const SEED_APPLICATIONS: Application[] = [
  {
    id: "app-eri",
    job_id: "job-eri",
    applied_at: "2026-09-12",
    workflow_state: "Interview",
    next_action: "Prepare interview — review RL scheduling papers",
    next_action_date: "2026-09-26",
    last_activity_at: iso("2026-09-23"),
  },
  {
    id: "app-vol",
    job_id: "job-vol",
    applied_at: "2026-09-22",
    workflow_state: "Applied",
    next_action: "Follow up if no reply by Oct 6",
    next_action_date: "2026-10-06",
    last_activity_at: iso("2026-09-22"),
  },
  {
    id: "app-sie",
    job_id: "job-sie",
    applied_at: null,
    workflow_state: "To Apply",
    next_action: "Submit application before deadline",
    next_action_date: "2026-09-28",
    last_activity_at: iso("2026-09-22"),
  },
  {
    id: "app-saa",
    job_id: "job-saa",
    applied_at: null,
    workflow_state: "Saved",
    next_action: "",
    next_action_date: null,
    last_activity_at: iso("2026-09-20"),
  },
  {
    id: "app-zen",
    job_id: "job-zen",
    applied_at: "2026-08-28",
    workflow_state: "Rejected",
    next_action: "",
    next_action_date: null,
    last_activity_at: iso("2026-09-16"),
  },
  {
    id: "app-sca",
    job_id: "job-sca",
    applied_at: null,
    workflow_state: "To Apply",
    next_action: "Tailor CV for embedded systems",
    next_action_date: "2026-09-25",
    last_activity_at: iso("2026-09-21"),
  },
];

export const SEED_EVENTS: ApplicationEvent[] = [
  // Ericsson — multi-step timeline
  {
    id: "ev-eri-1",
    application_id: "app-eri",
    event_type: "Job Saved",
    received_at: "2026-09-01",
    event_date: null,
    notes: "Found through the university thesis portal.",
    created_at: iso("2026-09-01"),
  },
  {
    id: "ev-eri-2",
    application_id: "app-eri",
    event_type: "Marked To Apply",
    received_at: "2026-09-05",
    event_date: null,
    notes: "Strong match with signal processing background.",
    created_at: iso("2026-09-05"),
  },
  {
    id: "ev-eri-3",
    application_id: "app-eri",
    event_type: "Application Submitted",
    received_at: "2026-09-12",
    event_date: null,
    notes: "Sent CV, transcript and a one-page proposal.",
    created_at: iso("2026-09-12"),
  },
  {
    id: "ev-eri-4",
    application_id: "app-eri",
    event_type: "Interview Invitation",
    received_at: "2026-09-18",
    event_date: "2026-09-26",
    notes: "Invitation from Anna at Radio Research. 45 minutes, Teams.",
    created_at: iso("2026-09-18"),
  },
  {
    id: "ev-eri-5",
    application_id: "app-eri",
    event_type: "Interview Round 1",
    received_at: null,
    event_date: "2026-09-26",
    notes: "Meet the supervisor and one senior researcher.",
    created_at: iso("2026-09-23"),
  },
  // Volvo
  {
    id: "ev-vol-1",
    application_id: "app-vol",
    event_type: "Job Saved",
    received_at: "2026-09-02",
    event_date: null,
    notes: "",
    created_at: iso("2026-09-02"),
  },
  {
    id: "ev-vol-2",
    application_id: "app-vol",
    event_type: "Application Submitted",
    received_at: "2026-09-22",
    event_date: null,
    notes: "Applied together with Marcus as a two-student thesis.",
    created_at: iso("2026-09-22"),
  },
  // Siemens Energy
  {
    id: "ev-sie-1",
    application_id: "app-sie",
    event_type: "Job Saved",
    received_at: "2026-08-20",
    event_date: null,
    notes: "",
    created_at: iso("2026-08-20"),
  },
  {
    id: "ev-sie-2",
    application_id: "app-sie",
    event_type: "Marked To Apply",
    received_at: "2026-09-22",
    event_date: null,
    notes: "Need a short motivation letter about turbine data.",
    created_at: iso("2026-09-22"),
  },
  // Saab
  {
    id: "ev-saa-1",
    application_id: "app-saa",
    event_type: "Job Saved",
    received_at: "2026-09-20",
    event_date: null,
    notes: "Check clearance requirements before applying.",
    created_at: iso("2026-09-20"),
  },
  // Zenseact
  {
    id: "ev-zen-1",
    application_id: "app-zen",
    event_type: "Job Saved",
    received_at: "2026-08-12",
    event_date: null,
    notes: "",
    created_at: iso("2026-08-12"),
  },
  {
    id: "ev-zen-2",
    application_id: "app-zen",
    event_type: "Application Submitted",
    received_at: "2026-08-28",
    event_date: null,
    notes: "",
    created_at: iso("2026-08-28"),
  },
  {
    id: "ev-zen-3",
    application_id: "app-zen",
    event_type: "Rejection Received",
    received_at: "2026-09-16",
    event_date: null,
    notes: "Polite rejection, invited to apply again next semester.",
    created_at: iso("2026-09-16"),
  },
  // Scania
  {
    id: "ev-sca-1",
    application_id: "app-sca",
    event_type: "Job Saved",
    received_at: "2026-09-12",
    event_date: null,
    notes: "",
    created_at: iso("2026-09-12"),
  },
  {
    id: "ev-sca-2",
    application_id: "app-sca",
    event_type: "Marked To Apply",
    received_at: "2026-09-21",
    event_date: null,
    notes: "",
    created_at: iso("2026-09-21"),
  },
];
